package org.fortheloss.sticknodespro;

/* JADX INFO: This class is generated by JADX */
public final class R {

    public static final class anim {
        public static final int fragment_fast_out_extra_slow_in = 0x7f010000;
    }

    public static final class animator {
        public static final int fragment_close_enter = 0x7f020000;
        public static final int fragment_close_exit = 0x7f020001;
        public static final int fragment_fade_enter = 0x7f020002;
        public static final int fragment_fade_exit = 0x7f020003;
        public static final int fragment_open_enter = 0x7f020004;
        public static final int fragment_open_exit = 0x7f020005;
    }

    public static final class attr {
        public static final int adSize = 0x7f030000;
        public static final int adSizes = 0x7f030001;
        public static final int adUnitId = 0x7f030002;
        public static final int alpha = 0x7f030003;
        public static final int buttonSize = 0x7f030004;
        public static final int circleCrop = 0x7f030005;
        public static final int colorScheme = 0x7f030006;
        public static final int font = 0x7f030007;
        public static final int fontProviderAuthority = 0x7f030008;
        public static final int fontProviderCerts = 0x7f030009;
        public static final int fontProviderFetchStrategy = 0x7f03000a;
        public static final int fontProviderFetchTimeout = 0x7f03000b;
        public static final int fontProviderPackage = 0x7f03000c;
        public static final int fontProviderQuery = 0x7f03000d;
        public static final int fontProviderSystemFontFamily = 0x7f03000e;
        public static final int fontStyle = 0x7f03000f;
        public static final int fontVariationSettings = 0x7f030010;
        public static final int fontWeight = 0x7f030011;
        public static final int imageAspectRatio = 0x7f030012;
        public static final int imageAspectRatioAdjust = 0x7f030013;
        public static final int lStar = 0x7f030014;
        public static final int nestedScrollViewStyle = 0x7f030015;
        public static final int queryPatterns = 0x7f030016;
        public static final int scopeUris = 0x7f030017;
        public static final int shortcutMatchRequired = 0x7f030018;
        public static final int ttcIndex = 0x7f030019;
    }

    public static final class bool {
        public static final int enable_system_alarm_service_default = 0x7f040000;
        public static final int enable_system_foreground_service_default = 0x7f040001;
        public static final int enable_system_job_service_default = 0x7f040002;
        public static final int workmanager_test_configuration = 0x7f040003;
    }

    public static final class color {
        public static final int androidx_core_ripple_material_light = 0x7f050000;
        public static final int androidx_core_secondary_text_default_material_light = 0x7f050001;
        public static final int browser_actions_bg_grey = 0x7f050002;
        public static final int browser_actions_divider_color = 0x7f050003;
        public static final int browser_actions_text_color = 0x7f050004;
        public static final int browser_actions_title_color = 0x7f050005;
        public static final int common_google_signin_btn_text_dark = 0x7f050006;
        public static final int common_google_signin_btn_text_dark_default = 0x7f050007;
        public static final int common_google_signin_btn_text_dark_disabled = 0x7f050008;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f050009;
        public static final int common_google_signin_btn_text_dark_pressed = 0x7f05000a;
        public static final int common_google_signin_btn_text_light = 0x7f05000b;
        public static final int common_google_signin_btn_text_light_default = 0x7f05000c;
        public static final int common_google_signin_btn_text_light_disabled = 0x7f05000d;
        public static final int common_google_signin_btn_text_light_focused = 0x7f05000e;
        public static final int common_google_signin_btn_text_light_pressed = 0x7f05000f;
        public static final int common_google_signin_btn_tint = 0x7f050010;
        public static final int notification_action_color_filter = 0x7f050011;
        public static final int notification_icon_bg_color = 0x7f050012;
    }

    public static final class dimen {
        public static final int browser_actions_context_menu_max_width = 0x7f060000;
        public static final int browser_actions_context_menu_min_padding = 0x7f060001;
        public static final int compat_button_inset_horizontal_material = 0x7f060002;
        public static final int compat_button_inset_vertical_material = 0x7f060003;
        public static final int compat_button_padding_horizontal_material = 0x7f060004;
        public static final int compat_button_padding_vertical_material = 0x7f060005;
        public static final int compat_control_corner_material = 0x7f060006;
        public static final int compat_notification_large_icon_max_height = 0x7f060007;
        public static final int compat_notification_large_icon_max_width = 0x7f060008;
        public static final int notification_action_icon_size = 0x7f060009;
        public static final int notification_action_text_size = 0x7f06000a;
        public static final int notification_big_circle_margin = 0x7f06000b;
        public static final int notification_content_margin_start = 0x7f06000c;
        public static final int notification_large_icon_height = 0x7f06000d;
        public static final int notification_large_icon_width = 0x7f06000e;
        public static final int notification_main_column_padding_top = 0x7f06000f;
        public static final int notification_media_narrow_margin = 0x7f060010;
        public static final int notification_right_icon_size = 0x7f060011;
        public static final int notification_right_side_padding_top = 0x7f060012;
        public static final int notification_small_icon_background_padding = 0x7f060013;
        public static final int notification_small_icon_size_as_large = 0x7f060014;
        public static final int notification_subtext_size = 0x7f060015;
        public static final int notification_top_pad = 0x7f060016;
        public static final int notification_top_pad_large_text = 0x7f060017;
    }

    public static final class drawable {
        public static final int _ic_launcher_foreground__0_res_0x7f070000 = 0x7f070000;
        public static final int admob_close_button_black_circle_white_cross = 0x7f070001;
        public static final int admob_close_button_white_circle_black_cross = 0x7f070002;
        public static final int admob_close_button_white_cross = 0x7f070003;
        public static final int common_full_open_on_phone = 0x7f070004;
        public static final int common_google_signin_btn_icon_dark = 0x7f070005;
        public static final int common_google_signin_btn_icon_dark_focused = 0x7f070006;
        public static final int common_google_signin_btn_icon_dark_normal = 0x7f070007;
        public static final int common_google_signin_btn_icon_dark_normal_background = 0x7f070008;
        public static final int common_google_signin_btn_icon_disabled = 0x7f070009;
        public static final int common_google_signin_btn_icon_light = 0x7f07000a;
        public static final int common_google_signin_btn_icon_light_focused = 0x7f07000b;
        public static final int common_google_signin_btn_icon_light_normal = 0x7f07000c;
        public static final int common_google_signin_btn_icon_light_normal_background = 0x7f07000d;
        public static final int common_google_signin_btn_text_dark = 0x7f07000e;
        public static final int common_google_signin_btn_text_dark_focused = 0x7f07000f;
        public static final int common_google_signin_btn_text_dark_normal = 0x7f070010;
        public static final int common_google_signin_btn_text_dark_normal_background = 0x7f070011;
        public static final int common_google_signin_btn_text_disabled = 0x7f070012;
        public static final int common_google_signin_btn_text_light = 0x7f070013;
        public static final int common_google_signin_btn_text_light_focused = 0x7f070014;
        public static final int common_google_signin_btn_text_light_normal = 0x7f070015;
        public static final int common_google_signin_btn_text_light_normal_background = 0x7f070016;
        public static final int googleg_disabled_color_18 = 0x7f070017;
        public static final int googleg_standard_color_18 = 0x7f070018;
        public static final int ic_launcher_background = 0x7f070019;
        public static final int ic_launcher_foreground = 0x7f07001a;
        public static final int notification_action_background = 0x7f07001b;
        public static final int notification_bg = 0x7f07001c;
        public static final int notification_bg_low = 0x7f07001d;
        public static final int notification_bg_low_normal = 0x7f07001e;
        public static final int notification_bg_low_pressed = 0x7f07001f;
        public static final int notification_bg_normal = 0x7f070020;
        public static final int notification_bg_normal_pressed = 0x7f070021;
        public static final int notification_icon_background = 0x7f070022;
        public static final int notification_template_icon_bg = 0x7f070023;
        public static final int notification_template_icon_low_bg = 0x7f070024;
        public static final int notification_tile_bg = 0x7f070025;
        public static final int notify_panel_notification_icon_bg = 0x7f070026;
        public static final int offline_dialog_background = 0x7f070027;
        public static final int offline_dialog_default_icon_42dp = 0x7f070028;
        public static final int sn_service_notif = 0x7f070029;
    }

    public static final class id {
        public static final int accessibility_action_clickable_span = 0x7f080000;
        public static final int accessibility_custom_action_0 = 0x7f080001;
        public static final int accessibility_custom_action_1 = 0x7f080002;
        public static final int accessibility_custom_action_10 = 0x7f080003;
        public static final int accessibility_custom_action_11 = 0x7f080004;
        public static final int accessibility_custom_action_12 = 0x7f080005;
        public static final int accessibility_custom_action_13 = 0x7f080006;
        public static final int accessibility_custom_action_14 = 0x7f080007;
        public static final int accessibility_custom_action_15 = 0x7f080008;
        public static final int accessibility_custom_action_16 = 0x7f080009;
        public static final int accessibility_custom_action_17 = 0x7f08000a;
        public static final int accessibility_custom_action_18 = 0x7f08000b;
        public static final int accessibility_custom_action_19 = 0x7f08000c;
        public static final int accessibility_custom_action_2 = 0x7f08000d;
        public static final int accessibility_custom_action_20 = 0x7f08000e;
        public static final int accessibility_custom_action_21 = 0x7f08000f;
        public static final int accessibility_custom_action_22 = 0x7f080010;
        public static final int accessibility_custom_action_23 = 0x7f080011;
        public static final int accessibility_custom_action_24 = 0x7f080012;
        public static final int accessibility_custom_action_25 = 0x7f080013;
        public static final int accessibility_custom_action_26 = 0x7f080014;
        public static final int accessibility_custom_action_27 = 0x7f080015;
        public static final int accessibility_custom_action_28 = 0x7f080016;
        public static final int accessibility_custom_action_29 = 0x7f080017;
        public static final int accessibility_custom_action_3 = 0x7f080018;
        public static final int accessibility_custom_action_30 = 0x7f080019;
        public static final int accessibility_custom_action_31 = 0x7f08001a;
        public static final int accessibility_custom_action_4 = 0x7f08001b;
        public static final int accessibility_custom_action_5 = 0x7f08001c;
        public static final int accessibility_custom_action_6 = 0x7f08001d;
        public static final int accessibility_custom_action_7 = 0x7f08001e;
        public static final int accessibility_custom_action_8 = 0x7f08001f;
        public static final int accessibility_custom_action_9 = 0x7f080020;
        public static final int action_container = 0x7f080021;
        public static final int action_divider = 0x7f080022;
        public static final int action_image = 0x7f080023;
        public static final int action_text = 0x7f080024;
        public static final int actions = 0x7f080025;
        public static final int adjust_height = 0x7f080026;
        public static final int adjust_width = 0x7f080027;
        public static final int async = 0x7f080028;
        public static final int auto = 0x7f080029;
        public static final int blocking = 0x7f08002a;
        public static final int browser_actions_header_text = 0x7f08002b;
        public static final int browser_actions_menu_item_icon = 0x7f08002c;
        public static final int browser_actions_menu_item_text = 0x7f08002d;
        public static final int browser_actions_menu_items = 0x7f08002e;
        public static final int browser_actions_menu_view = 0x7f08002f;
        public static final int chronometer = 0x7f080030;
        public static final int dark = 0x7f080031;
        public static final int dialog_button = 0x7f080032;
        public static final int forever = 0x7f080033;
        public static final int fragment_container_view_tag = 0x7f080034;
        public static final int icon = 0x7f080035;
        public static final int icon_group = 0x7f080036;
        public static final int icon_only = 0x7f080037;
        public static final int info = 0x7f080038;
        public static final int italic = 0x7f080039;
        public static final int layout = 0x7f08003a;
        public static final int light = 0x7f08003b;
        public static final int line1 = 0x7f08003c;
        public static final int line3 = 0x7f08003d;
        public static final int none = 0x7f08003e;
        public static final int normal = 0x7f08003f;
        public static final int notification_background = 0x7f080040;
        public static final int notification_main_column = 0x7f080041;
        public static final int notification_main_column_container = 0x7f080042;
        public static final int offline_dialog_advertiser_name = 0x7f080043;
        public static final int offline_dialog_image = 0x7f080044;
        public static final int offline_dialog_text = 0x7f080045;
        public static final int right_icon = 0x7f080046;
        public static final int right_side = 0x7f080047;
        public static final int special_effects_controller_view_tag = 0x7f080048;
        public static final int standard = 0x7f080049;
        public static final int tag_accessibility_actions = 0x7f08004a;
        public static final int tag_accessibility_clickable_spans = 0x7f08004b;
        public static final int tag_accessibility_heading = 0x7f08004c;
        public static final int tag_accessibility_pane_title = 0x7f08004d;
        public static final int tag_on_apply_window_listener = 0x7f08004e;
        public static final int tag_on_receive_content_listener = 0x7f08004f;
        public static final int tag_on_receive_content_mime_types = 0x7f080050;
        public static final int tag_screen_reader_focusable = 0x7f080051;
        public static final int tag_state_description = 0x7f080052;
        public static final int tag_transition_group = 0x7f080053;
        public static final int tag_unhandled_key_event_manager = 0x7f080054;
        public static final int tag_unhandled_key_listeners = 0x7f080055;
        public static final int tag_window_insets_animation_callback = 0x7f080056;
        public static final int text = 0x7f080057;
        public static final int text2 = 0x7f080058;
        public static final int time = 0x7f080059;
        public static final int title = 0x7f08005a;
        public static final int view_tree_lifecycle_owner = 0x7f08005b;
        public static final int view_tree_on_back_pressed_dispatcher_owner = 0x7f08005c;
        public static final int view_tree_saved_state_registry_owner = 0x7f08005d;
        public static final int view_tree_view_model_store_owner = 0x7f08005e;
        public static final int visible_removing_fragment_view_tag = 0x7f08005f;
        public static final int wide = 0x7f080060;
    }

    public static final class integer {
        public static final int google_play_services_version = 0x7f090000;
        public static final int status_bar_notification_info_maxnum = 0x7f090001;
    }

    public static final class layout {
        public static final int admob_empty_layout = 0x7f0a0000;
        public static final int browser_actions_context_menu_page = 0x7f0a0001;
        public static final int browser_actions_context_menu_row = 0x7f0a0002;
        public static final int custom_dialog = 0x7f0a0003;
        public static final int notification_action = 0x7f0a0004;
        public static final int notification_action_tombstone = 0x7f0a0005;
        public static final int notification_template_custom_big = 0x7f0a0006;
        public static final int notification_template_icon_group = 0x7f0a0007;
        public static final int notification_template_part_chronometer = 0x7f0a0008;
        public static final int notification_template_part_time = 0x7f0a0009;
        public static final int offline_ads_dialog = 0x7f0a000a;
    }

    public static final class mipmap {
        public static final int ic_launcher = 0x7f0b0000;
        public static final int ic_launcher_background = 0x7f0b0001;
        public static final int ic_launcher_foreground = 0x7f0b0002;
        public static final int ic_launcher_round = 0x7f0b0003;
    }

    public static final class raw {
        public static final int firebase_common_keep = 0x7f0c0000;
        public static final int firebase_crashlytics_keep = 0x7f0c0001;
    }

    public static final class string {
        public static final int admob_id = 0x7f0d0000;
        public static final int admob_interstitial_ad_id = 0x7f0d0001;
        public static final int amazon_app_key = 0x7f0d0002;
        public static final int androidx_startup = 0x7f0d0003;
        public static final int app_id = 0x7f0d0004;
        public static final int app_name = 0x7f0d0005;
        public static final int com_google_firebase_crashlytics_mapping_file_id = 0x7f0d0006;
        public static final int common_google_play_services_enable_button = 0x7f0d0007;
        public static final int common_google_play_services_enable_text = 0x7f0d0008;
        public static final int common_google_play_services_enable_title = 0x7f0d0009;
        public static final int common_google_play_services_install_button = 0x7f0d000a;
        public static final int common_google_play_services_install_text = 0x7f0d000b;
        public static final int common_google_play_services_install_title = 0x7f0d000c;
        public static final int common_google_play_services_notification_channel_name = 0x7f0d000d;
        public static final int common_google_play_services_notification_ticker = 0x7f0d000e;
        public static final int common_google_play_services_unknown_issue = 0x7f0d000f;
        public static final int common_google_play_services_unsupported_text = 0x7f0d0010;
        public static final int common_google_play_services_update_button = 0x7f0d0011;
        public static final int common_google_play_services_update_text = 0x7f0d0012;
        public static final int common_google_play_services_update_title = 0x7f0d0013;
        public static final int common_google_play_services_updating_text = 0x7f0d0014;
        public static final int common_google_play_services_wear_update_text = 0x7f0d0015;
        public static final int common_open_on_phone = 0x7f0d0016;
        public static final int common_signin_button_text = 0x7f0d0017;
        public static final int common_signin_button_text_long = 0x7f0d0018;
        public static final int copy_toast_msg = 0x7f0d0019;
        public static final int default_web_client_id = 0x7f0d001a;
        public static final int facebook_app_id = 0x7f0d001b;
        public static final int fallback_menu_item_copy_link = 0x7f0d001c;
        public static final int fallback_menu_item_open_in_browser = 0x7f0d001d;
        public static final int fallback_menu_item_share_link = 0x7f0d001e;
        public static final int firebase_database_url = 0x7f0d001f;
        public static final int gcm_defaultSenderId = 0x7f0d0020;
        public static final int google_api_key = 0x7f0d0021;
        public static final int google_app_id = 0x7f0d0022;
        public static final int google_crash_reporting_api_key = 0x7f0d0023;
        public static final int google_storage_bucket = 0x7f0d0024;
        public static final int leaderboard_id = 0x7f0d0025;
        public static final int native_body = 0x7f0d0026;
        public static final int native_headline = 0x7f0d0027;
        public static final int native_media_view = 0x7f0d0028;
        public static final int notifications_permission_confirm = 0x7f0d0029;
        public static final int notifications_permission_decline = 0x7f0d002a;
        public static final int notifications_permission_title = 0x7f0d002b;
        public static final int offline_dialog_image_description = 0x7f0d002c;
        public static final int offline_dialog_text = 0x7f0d002d;
        public static final int offline_notification_title = 0x7f0d002e;
        public static final int offline_notification_title_with_advertiser = 0x7f0d002f;
        public static final int offline_opt_in_confirm = 0x7f0d0030;
        public static final int offline_opt_in_decline = 0x7f0d0031;
        public static final int offline_opt_in_message = 0x7f0d0032;
        public static final int offline_opt_in_title = 0x7f0d0033;
        public static final int project_id = 0x7f0d0034;
        public static final int s1 = 0x7f0d0035;
        public static final int s2 = 0x7f0d0036;
        public static final int s3 = 0x7f0d0037;
        public static final int s4 = 0x7f0d0038;
        public static final int s5 = 0x7f0d0039;
        public static final int s6 = 0x7f0d003a;
        public static final int s7 = 0x7f0d003b;
        public static final int status_bar_notification_info_overflow = 0x7f0d003c;
        public static final int watermark_label_prefix = 0x7f0d003d;
    }

    public static final class style {
        public static final int TextAppearance_Compat_Notification = 0x7f0e0000;
        public static final int TextAppearance_Compat_Notification_Info = 0x7f0e0001;
        public static final int TextAppearance_Compat_Notification_Line2 = 0x7f0e0002;
        public static final int TextAppearance_Compat_Notification_Time = 0x7f0e0003;
        public static final int TextAppearance_Compat_Notification_Title = 0x7f0e0004;
        public static final int Theme_Games_Transparent = 0x7f0e0005;
        public static final int Theme_IAPTheme = 0x7f0e0006;
        public static final int Widget_Compat_NotificationActionContainer = 0x7f0e0007;
        public static final int Widget_Compat_NotificationActionText = 0x7f0e0008;
    }

    public static final class xml {
        public static final int gma_ad_services_config = 0x7f100000;
        public static final int image_share_filepaths = 0x7f100001;
        public static final int provider_paths = 0x7f100002;
    }
}
