package com.google.android.gms.internal.fido;

/* compiled from: com.google.android.gms:play-services-fido@@20.0.1 */
/* loaded from: classes.dex */
public final class zzh {
    public static final com.google.android.gms.internal.fido.zzbj zzA = null;
    public static final com.google.android.gms.internal.fido.zzbj zzB = null;
    public static final com.google.android.gms.internal.fido.zzbj zzC = null;
    public static final com.google.android.gms.internal.fido.zzbj zzD = null;
    public static final com.google.android.gms.internal.fido.zzbj zza = null;
    public static final com.google.android.gms.internal.fido.zzbj zzb = null;
    public static final com.google.android.gms.internal.fido.zzbj zzc = null;
    public static final com.google.android.gms.internal.fido.zzbj zzd = null;
    public static final com.google.android.gms.internal.fido.zzbj zze = null;
    public static final com.google.android.gms.internal.fido.zzbj zzf = null;
    public static final com.google.android.gms.internal.fido.zzbj zzg = null;
    public static final com.google.android.gms.internal.fido.zzbj zzh = null;
    public static final com.google.android.gms.internal.fido.zzbj zzi = null;
    public static final com.google.android.gms.internal.fido.zzbj zzj = null;
    public static final com.google.android.gms.internal.fido.zzbj zzk = null;
    public static final com.google.android.gms.internal.fido.zzbj zzl = null;
    public static final com.google.android.gms.internal.fido.zzbj zzm = null;
    public static final com.google.android.gms.internal.fido.zzbj zzn = null;
    public static final com.google.android.gms.internal.fido.zzbj zzo = null;
    public static final com.google.android.gms.internal.fido.zzbj zzp = null;
    public static final com.google.android.gms.internal.fido.zzbj zzq = null;
    public static final com.google.android.gms.internal.fido.zzbj zzr = null;
    public static final com.google.android.gms.internal.fido.zzbj zzs = null;
    public static final com.google.android.gms.internal.fido.zzbj zzt = null;
    public static final com.google.android.gms.internal.fido.zzbj zzu = null;
    public static final com.google.android.gms.internal.fido.zzbj zzv = null;
    public static final com.google.android.gms.internal.fido.zzbj zzw = null;
    public static final com.google.android.gms.internal.fido.zzbj zzx = null;
    public static final com.google.android.gms.internal.fido.zzbj zzy = null;
    public static final com.google.android.gms.internal.fido.zzbj zzz = null;

    static {
            java.lang.String r0 = "id"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zza = r0
            java.lang.String r0 = "type"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzb = r0
            java.lang.String r0 = "transports"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzc = r0
            java.lang.String r0 = "name"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzd = r0
            java.lang.String r0 = "icon"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zze = r0
            java.lang.String r0 = "displayName"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzf = r0
            java.lang.String r0 = "alg"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzg = r0
            java.lang.String r0 = "plat"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzh = r0
            java.lang.String r0 = "rk"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzi = r0
            java.lang.String r0 = "clientPin"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzj = r0
            java.lang.String r0 = "up"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzk = r0
            java.lang.String r0 = "uv"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzl = r0
            java.lang.String r0 = "alwaysUv"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzm = r0
            java.lang.String r0 = "credMgmt"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzn = r0
            java.lang.String r0 = "authnrCfg"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzo = r0
            java.lang.String r0 = "bioEnroll"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzp = r0
            java.lang.String r0 = "largeBlobs"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzq = r0
            java.lang.String r0 = "pinUvAuthToken"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzr = r0
            java.lang.String r0 = "noMcGaPermissionsWithClientPin"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzs = r0
            java.lang.String r0 = "ep"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzt = r0
            java.lang.String r0 = "uvBioEnroll"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzu = r0
            java.lang.String r0 = "uvAcfg"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzv = r0
            java.lang.String r0 = "setMinPINLength"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzw = r0
            java.lang.String r0 = "makeCredUvNotRqd"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzx = r0
            java.lang.String r0 = "credentialMgmtPreview"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzy = r0
            java.lang.String r0 = "userVerificationMgmtPreview"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzz = r0
            java.lang.String r0 = "uvm"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzA = r0
            java.lang.String r0 = "multiAssertion"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzB = r0
            java.lang.String r0 = "sessionId"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzC = r0
            java.lang.String r0 = "google_userVerificationOrigin"
            com.google.android.gms.internal.fido.zzbj r0 = com.google.android.gms.internal.fido.zzbk.zzb(r0)
            com.google.android.gms.internal.fido.zzh.zzD = r0
            return
    }
}
