package com.google.android.gms.common.api.internal;

import com.google.android.gms.common.api.Result;

/* compiled from: com.google.android.gms:play-services-base@@18.4.0 */
/* loaded from: classes.dex */
public final class zacp<R extends com.google.android.gms.common.api.Result> extends com.google.android.gms.common.api.PendingResult<R> {
    private final com.google.android.gms.common.api.Status zaa;

    public zacp(com.google.android.gms.common.api.Status r3) {
            r2 = this;
            r2.<init>()
            java.lang.String r0 = "Status must not be null"
            com.google.android.gms.common.internal.Preconditions.checkNotNull(r3, r0)
            boolean r0 = r3.isSuccess()
            r0 = r0 ^ 1
            java.lang.String r1 = "Status must not be success"
            com.google.android.gms.common.internal.Preconditions.checkArgument(r0, r1)
            r2.zaa = r3
            return
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final void addStatusListener(com.google.android.gms.common.api.PendingResult.StatusListener r2) {
            r1 = this;
            java.lang.UnsupportedOperationException r2 = new java.lang.UnsupportedOperationException
            java.lang.String r0 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r2.<init>(r0)
            throw r2
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final R await() {
            r2 = this;
            java.lang.UnsupportedOperationException r0 = new java.lang.UnsupportedOperationException
            java.lang.String r1 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r0.<init>(r1)
            throw r0
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final R await(long r1, java.util.concurrent.TimeUnit r3) {
            r0 = this;
            java.lang.UnsupportedOperationException r1 = new java.lang.UnsupportedOperationException
            java.lang.String r2 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r1.<init>(r2)
            throw r1
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final void cancel() {
            r2 = this;
            java.lang.UnsupportedOperationException r0 = new java.lang.UnsupportedOperationException
            java.lang.String r1 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r0.<init>(r1)
            throw r0
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final boolean isCanceled() {
            r2 = this;
            java.lang.UnsupportedOperationException r0 = new java.lang.UnsupportedOperationException
            java.lang.String r1 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r0.<init>(r1)
            throw r0
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final void setResultCallback(com.google.android.gms.common.api.ResultCallback<? super R> r2) {
            r1 = this;
            java.lang.UnsupportedOperationException r2 = new java.lang.UnsupportedOperationException
            java.lang.String r0 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r2.<init>(r0)
            throw r2
    }

    @Override // com.google.android.gms.common.api.PendingResult
    public final void setResultCallback(com.google.android.gms.common.api.ResultCallback<? super R> r1, long r2, java.util.concurrent.TimeUnit r4) {
            r0 = this;
            java.lang.UnsupportedOperationException r1 = new java.lang.UnsupportedOperationException
            java.lang.String r2 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r1.<init>(r2)
            throw r1
    }

    @Override // com.google.android.gms.common.api.PendingResult
    @com.google.android.gms.common.internal.ShowFirstParty
    public final <S extends com.google.android.gms.common.api.Result> com.google.android.gms.common.api.TransformedResult<S> then(com.google.android.gms.common.api.ResultTransform<? super R, ? extends S> r2) {
            r1 = this;
            java.lang.UnsupportedOperationException r2 = new java.lang.UnsupportedOperationException
            java.lang.String r0 = "Operation not supported on PendingResults generated by ResultTransform.createFailedResult()"
            r2.<init>(r0)
            throw r2
    }

    final com.google.android.gms.common.api.Status zaa() {
            r1 = this;
            com.google.android.gms.common.api.Status r0 = r1.zaa
            return r0
    }
}
