package org.apache.commons.lang3.text.translate;

@java.lang.Deprecated
/* loaded from: classes2.dex */
public class EntityArrays {
    private static final java.lang.String[][] APOS_ESCAPE = null;
    private static final java.lang.String[][] APOS_UNESCAPE = null;
    private static final java.lang.String[][] BASIC_ESCAPE = null;
    private static final java.lang.String[][] BASIC_UNESCAPE = null;
    private static final java.lang.String[][] HTML40_EXTENDED_ESCAPE = null;
    private static final java.lang.String[][] HTML40_EXTENDED_UNESCAPE = null;
    private static final java.lang.String[][] ISO8859_1_ESCAPE = null;
    private static final java.lang.String[][] ISO8859_1_UNESCAPE = null;
    private static final java.lang.String[][] JAVA_CTRL_CHARS_ESCAPE = null;
    private static final java.lang.String[][] JAVA_CTRL_CHARS_UNESCAPE = null;

    static {
            r0 = 96
            java.lang.String[][] r1 = new java.lang.String[r0][]
            java.lang.String r2 = " "
            java.lang.String r3 = "&nbsp;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r3}
            r3 = 0
            r1[r3] = r2
            java.lang.String r2 = "¡"
            java.lang.String r4 = "&iexcl;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r4}
            r4 = 1
            r1[r4] = r2
            java.lang.String r2 = "¢"
            java.lang.String r5 = "&cent;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r5}
            r5 = 2
            r1[r5] = r2
            java.lang.String r2 = "£"
            java.lang.String r6 = "&pound;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r6}
            r6 = 3
            r1[r6] = r2
            java.lang.String r2 = "¤"
            java.lang.String r7 = "&curren;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r7}
            r7 = 4
            r1[r7] = r2
            java.lang.String r2 = "¥"
            java.lang.String r8 = "&yen;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r8}
            r8 = 5
            r1[r8] = r2
            java.lang.String r2 = "¦"
            java.lang.String r9 = "&brvbar;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r9}
            r9 = 6
            r1[r9] = r2
            java.lang.String r2 = "§"
            java.lang.String r10 = "&sect;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r10}
            r10 = 7
            r1[r10] = r2
            java.lang.String r2 = "¨"
            java.lang.String r11 = "&uml;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r11}
            r11 = 8
            r1[r11] = r2
            java.lang.String r2 = "©"
            java.lang.String r12 = "&copy;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r12}
            r12 = 9
            r1[r12] = r2
            java.lang.String r2 = "ª"
            java.lang.String r13 = "&ordf;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r13}
            r13 = 10
            r1[r13] = r2
            java.lang.String r2 = "«"
            java.lang.String r14 = "&laquo;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r14}
            r14 = 11
            r1[r14] = r2
            java.lang.String r2 = "¬"
            java.lang.String r15 = "&not;"
            java.lang.String[] r2 = new java.lang.String[]{r2, r15}
            r15 = 12
            r1[r15] = r2
            java.lang.String r2 = "\u00ad"
            java.lang.String r0 = "&shy;"
            java.lang.String[] r0 = new java.lang.String[]{r2, r0}
            r2 = 13
            r1[r2] = r0
            java.lang.String r0 = "®"
            java.lang.String r2 = "&reg;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 14
            r1[r2] = r0
            java.lang.String r0 = "¯"
            java.lang.String r2 = "&macr;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 15
            r1[r2] = r0
            java.lang.String r0 = "°"
            java.lang.String r2 = "&deg;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 16
            r1[r2] = r0
            java.lang.String r0 = "±"
            java.lang.String r2 = "&plusmn;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 17
            r1[r2] = r0
            java.lang.String r0 = "²"
            java.lang.String r2 = "&sup2;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 18
            r1[r2] = r0
            java.lang.String r0 = "³"
            java.lang.String r2 = "&sup3;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 19
            r1[r2] = r0
            java.lang.String r0 = "´"
            java.lang.String r2 = "&acute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 20
            r1[r2] = r0
            java.lang.String r0 = "µ"
            java.lang.String r2 = "&micro;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 21
            r1[r2] = r0
            java.lang.String r0 = "¶"
            java.lang.String r2 = "&para;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 22
            r1[r2] = r0
            java.lang.String r0 = "·"
            java.lang.String r2 = "&middot;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 23
            r1[r2] = r0
            java.lang.String r0 = "¸"
            java.lang.String r2 = "&cedil;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 24
            r1[r2] = r0
            java.lang.String r0 = "¹"
            java.lang.String r2 = "&sup1;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 25
            r1[r2] = r0
            java.lang.String r0 = "º"
            java.lang.String r2 = "&ordm;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 26
            r1[r2] = r0
            java.lang.String r0 = "»"
            java.lang.String r2 = "&raquo;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 27
            r1[r2] = r0
            java.lang.String r0 = "¼"
            java.lang.String r2 = "&frac14;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 28
            r1[r2] = r0
            java.lang.String r0 = "½"
            java.lang.String r2 = "&frac12;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 29
            r1[r2] = r0
            java.lang.String r0 = "¾"
            java.lang.String r2 = "&frac34;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 30
            r1[r2] = r0
            java.lang.String r0 = "¿"
            java.lang.String r2 = "&iquest;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 31
            r1[r2] = r0
            java.lang.String r0 = "À"
            java.lang.String r2 = "&Agrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 32
            r1[r2] = r0
            java.lang.String r0 = "Á"
            java.lang.String r2 = "&Aacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 33
            r1[r2] = r0
            java.lang.String r0 = "Â"
            java.lang.String r2 = "&Acirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 34
            r1[r2] = r0
            java.lang.String r0 = "Ã"
            java.lang.String r2 = "&Atilde;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 35
            r1[r2] = r0
            java.lang.String r0 = "Ä"
            java.lang.String r2 = "&Auml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 36
            r1[r2] = r0
            java.lang.String r0 = "Å"
            java.lang.String r2 = "&Aring;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 37
            r1[r2] = r0
            java.lang.String r0 = "Æ"
            java.lang.String r2 = "&AElig;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 38
            r1[r2] = r0
            java.lang.String r0 = "Ç"
            java.lang.String r2 = "&Ccedil;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 39
            r1[r2] = r0
            java.lang.String r0 = "È"
            java.lang.String r2 = "&Egrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 40
            r1[r2] = r0
            java.lang.String r0 = "É"
            java.lang.String r2 = "&Eacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 41
            r1[r2] = r0
            java.lang.String r0 = "Ê"
            java.lang.String r2 = "&Ecirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 42
            r1[r2] = r0
            java.lang.String r0 = "Ë"
            java.lang.String r2 = "&Euml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 43
            r1[r2] = r0
            java.lang.String r0 = "Ì"
            java.lang.String r2 = "&Igrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 44
            r1[r2] = r0
            java.lang.String r0 = "Í"
            java.lang.String r2 = "&Iacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 45
            r1[r2] = r0
            java.lang.String r0 = "Î"
            java.lang.String r2 = "&Icirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 46
            r1[r2] = r0
            java.lang.String r0 = "Ï"
            java.lang.String r2 = "&Iuml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 47
            r1[r2] = r0
            java.lang.String r0 = "Ð"
            java.lang.String r2 = "&ETH;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 48
            r1[r2] = r0
            java.lang.String r0 = "Ñ"
            java.lang.String r2 = "&Ntilde;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 49
            r1[r2] = r0
            java.lang.String r0 = "Ò"
            java.lang.String r2 = "&Ograve;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 50
            r1[r2] = r0
            java.lang.String r0 = "Ó"
            java.lang.String r2 = "&Oacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 51
            r1[r2] = r0
            java.lang.String r0 = "Ô"
            java.lang.String r2 = "&Ocirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 52
            r1[r2] = r0
            java.lang.String r0 = "Õ"
            java.lang.String r2 = "&Otilde;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 53
            r1[r2] = r0
            java.lang.String r0 = "Ö"
            java.lang.String r2 = "&Ouml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 54
            r1[r2] = r0
            java.lang.String r0 = "×"
            java.lang.String r2 = "&times;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 55
            r1[r2] = r0
            java.lang.String r0 = "Ø"
            java.lang.String r2 = "&Oslash;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 56
            r1[r2] = r0
            java.lang.String r0 = "Ù"
            java.lang.String r2 = "&Ugrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 57
            r1[r2] = r0
            java.lang.String r0 = "Ú"
            java.lang.String r2 = "&Uacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 58
            r1[r2] = r0
            java.lang.String r0 = "Û"
            java.lang.String r2 = "&Ucirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 59
            r1[r2] = r0
            java.lang.String r0 = "Ü"
            java.lang.String r2 = "&Uuml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 60
            r1[r2] = r0
            java.lang.String r0 = "Ý"
            java.lang.String r2 = "&Yacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 61
            r1[r2] = r0
            java.lang.String r0 = "Þ"
            java.lang.String r2 = "&THORN;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 62
            r1[r2] = r0
            java.lang.String r0 = "ß"
            java.lang.String r2 = "&szlig;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 63
            r1[r2] = r0
            java.lang.String r0 = "à"
            java.lang.String r2 = "&agrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 64
            r1[r2] = r0
            java.lang.String r0 = "á"
            java.lang.String r2 = "&aacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 65
            r1[r2] = r0
            java.lang.String r0 = "â"
            java.lang.String r2 = "&acirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 66
            r1[r2] = r0
            java.lang.String r0 = "ã"
            java.lang.String r2 = "&atilde;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 67
            r1[r2] = r0
            java.lang.String r0 = "ä"
            java.lang.String r2 = "&auml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 68
            r1[r2] = r0
            java.lang.String r0 = "å"
            java.lang.String r2 = "&aring;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 69
            r1[r2] = r0
            java.lang.String r0 = "æ"
            java.lang.String r2 = "&aelig;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 70
            r1[r2] = r0
            java.lang.String r0 = "ç"
            java.lang.String r2 = "&ccedil;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 71
            r1[r2] = r0
            java.lang.String r0 = "è"
            java.lang.String r2 = "&egrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 72
            r1[r2] = r0
            java.lang.String r0 = "é"
            java.lang.String r2 = "&eacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 73
            r1[r2] = r0
            java.lang.String r0 = "ê"
            java.lang.String r2 = "&ecirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 74
            r1[r2] = r0
            java.lang.String r0 = "ë"
            java.lang.String r2 = "&euml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 75
            r1[r2] = r0
            java.lang.String r0 = "ì"
            java.lang.String r2 = "&igrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 76
            r1[r2] = r0
            java.lang.String r0 = "í"
            java.lang.String r2 = "&iacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 77
            r1[r2] = r0
            java.lang.String r0 = "î"
            java.lang.String r2 = "&icirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 78
            r1[r2] = r0
            java.lang.String r0 = "ï"
            java.lang.String r2 = "&iuml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 79
            r1[r2] = r0
            java.lang.String r0 = "ð"
            java.lang.String r2 = "&eth;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 80
            r1[r2] = r0
            java.lang.String r0 = "ñ"
            java.lang.String r2 = "&ntilde;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 81
            r1[r2] = r0
            java.lang.String r0 = "ò"
            java.lang.String r2 = "&ograve;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 82
            r1[r2] = r0
            java.lang.String r0 = "ó"
            java.lang.String r2 = "&oacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 83
            r1[r2] = r0
            java.lang.String r0 = "ô"
            java.lang.String r2 = "&ocirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 84
            r1[r2] = r0
            java.lang.String r0 = "õ"
            java.lang.String r2 = "&otilde;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 85
            r1[r2] = r0
            java.lang.String r0 = "ö"
            java.lang.String r2 = "&ouml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 86
            r1[r2] = r0
            java.lang.String r0 = "÷"
            java.lang.String r2 = "&divide;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 87
            r1[r2] = r0
            java.lang.String r0 = "ø"
            java.lang.String r2 = "&oslash;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 88
            r1[r2] = r0
            java.lang.String r0 = "ù"
            java.lang.String r2 = "&ugrave;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 89
            r1[r2] = r0
            java.lang.String r0 = "ú"
            java.lang.String r2 = "&uacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 90
            r1[r2] = r0
            java.lang.String r0 = "û"
            java.lang.String r2 = "&ucirc;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 91
            r1[r2] = r0
            java.lang.String r0 = "ü"
            java.lang.String r2 = "&uuml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 92
            r1[r2] = r0
            java.lang.String r0 = "ý"
            java.lang.String r2 = "&yacute;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 93
            r1[r2] = r0
            java.lang.String r0 = "þ"
            java.lang.String r2 = "&thorn;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 94
            r1[r2] = r0
            java.lang.String r0 = "ÿ"
            java.lang.String r2 = "&yuml;"
            java.lang.String[] r0 = new java.lang.String[]{r0, r2}
            r2 = 95
            r1[r2] = r0
            org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE = r1
            java.lang.String[][] r0 = invert(r1)
            org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE = r0
            r0 = 152(0x98, float:2.13E-43)
            java.lang.String[][] r0 = new java.lang.String[r0][]
            java.lang.String r1 = "ƒ"
            java.lang.String r2 = "&fnof;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r3] = r1
            java.lang.String r1 = "Α"
            java.lang.String r2 = "&Alpha;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r4] = r1
            java.lang.String r1 = "Β"
            java.lang.String r2 = "&Beta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r5] = r1
            java.lang.String r1 = "Γ"
            java.lang.String r2 = "&Gamma;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r6] = r1
            java.lang.String r1 = "Δ"
            java.lang.String r2 = "&Delta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r7] = r1
            java.lang.String r1 = "Ε"
            java.lang.String r2 = "&Epsilon;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r8] = r1
            java.lang.String r1 = "Ζ"
            java.lang.String r2 = "&Zeta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r9] = r1
            java.lang.String r1 = "Η"
            java.lang.String r2 = "&Eta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r10] = r1
            java.lang.String r1 = "Θ"
            java.lang.String r2 = "&Theta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r11] = r1
            java.lang.String r1 = "Ι"
            java.lang.String r2 = "&Iota;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r12] = r1
            java.lang.String r1 = "Κ"
            java.lang.String r2 = "&Kappa;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r13] = r1
            java.lang.String r1 = "Λ"
            java.lang.String r2 = "&Lambda;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r14] = r1
            java.lang.String r1 = "Μ"
            java.lang.String r2 = "&Mu;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r15] = r1
            java.lang.String r1 = "Ν"
            java.lang.String r2 = "&Nu;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 13
            r0[r2] = r1
            java.lang.String r1 = "Ξ"
            java.lang.String r2 = "&Xi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 14
            r0[r2] = r1
            java.lang.String r1 = "Ο"
            java.lang.String r2 = "&Omicron;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 15
            r0[r2] = r1
            java.lang.String r1 = "Π"
            java.lang.String r2 = "&Pi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 16
            r0[r2] = r1
            java.lang.String r1 = "Ρ"
            java.lang.String r2 = "&Rho;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 17
            r0[r2] = r1
            java.lang.String r1 = "Σ"
            java.lang.String r2 = "&Sigma;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 18
            r0[r2] = r1
            java.lang.String r1 = "Τ"
            java.lang.String r2 = "&Tau;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 19
            r0[r2] = r1
            java.lang.String r1 = "Υ"
            java.lang.String r2 = "&Upsilon;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 20
            r0[r2] = r1
            java.lang.String r1 = "Φ"
            java.lang.String r2 = "&Phi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 21
            r0[r2] = r1
            java.lang.String r1 = "Χ"
            java.lang.String r2 = "&Chi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 22
            r0[r2] = r1
            java.lang.String r1 = "Ψ"
            java.lang.String r2 = "&Psi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 23
            r0[r2] = r1
            java.lang.String r1 = "Ω"
            java.lang.String r2 = "&Omega;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 24
            r0[r2] = r1
            java.lang.String r1 = "α"
            java.lang.String r2 = "&alpha;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 25
            r0[r2] = r1
            java.lang.String r1 = "β"
            java.lang.String r2 = "&beta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 26
            r0[r2] = r1
            java.lang.String r1 = "γ"
            java.lang.String r2 = "&gamma;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 27
            r0[r2] = r1
            java.lang.String r1 = "δ"
            java.lang.String r2 = "&delta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 28
            r0[r2] = r1
            java.lang.String r1 = "ε"
            java.lang.String r2 = "&epsilon;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 29
            r0[r2] = r1
            java.lang.String r1 = "ζ"
            java.lang.String r2 = "&zeta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 30
            r0[r2] = r1
            java.lang.String r1 = "η"
            java.lang.String r2 = "&eta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 31
            r0[r2] = r1
            java.lang.String r1 = "θ"
            java.lang.String r2 = "&theta;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 32
            r0[r2] = r1
            java.lang.String r1 = "ι"
            java.lang.String r2 = "&iota;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 33
            r0[r2] = r1
            java.lang.String r1 = "κ"
            java.lang.String r2 = "&kappa;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 34
            r0[r2] = r1
            java.lang.String r1 = "λ"
            java.lang.String r2 = "&lambda;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 35
            r0[r2] = r1
            java.lang.String r1 = "μ"
            java.lang.String r2 = "&mu;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 36
            r0[r2] = r1
            java.lang.String r1 = "ν"
            java.lang.String r2 = "&nu;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 37
            r0[r2] = r1
            java.lang.String r1 = "ξ"
            java.lang.String r2 = "&xi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 38
            r0[r2] = r1
            java.lang.String r1 = "ο"
            java.lang.String r2 = "&omicron;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 39
            r0[r2] = r1
            java.lang.String r1 = "π"
            java.lang.String r2 = "&pi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 40
            r0[r2] = r1
            java.lang.String r1 = "ρ"
            java.lang.String r2 = "&rho;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 41
            r0[r2] = r1
            java.lang.String r1 = "ς"
            java.lang.String r2 = "&sigmaf;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 42
            r0[r2] = r1
            java.lang.String r1 = "σ"
            java.lang.String r2 = "&sigma;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 43
            r0[r2] = r1
            java.lang.String r1 = "τ"
            java.lang.String r2 = "&tau;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 44
            r0[r2] = r1
            java.lang.String r1 = "υ"
            java.lang.String r2 = "&upsilon;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 45
            r0[r2] = r1
            java.lang.String r1 = "φ"
            java.lang.String r2 = "&phi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 46
            r0[r2] = r1
            java.lang.String r1 = "χ"
            java.lang.String r2 = "&chi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 47
            r0[r2] = r1
            java.lang.String r1 = "ψ"
            java.lang.String r2 = "&psi;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 48
            r0[r2] = r1
            java.lang.String r1 = "ω"
            java.lang.String r2 = "&omega;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 49
            r0[r2] = r1
            java.lang.String r1 = "ϑ"
            java.lang.String r2 = "&thetasym;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 50
            r0[r2] = r1
            java.lang.String r1 = "ϒ"
            java.lang.String r2 = "&upsih;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 51
            r0[r2] = r1
            java.lang.String r1 = "ϖ"
            java.lang.String r2 = "&piv;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 52
            r0[r2] = r1
            java.lang.String r1 = "•"
            java.lang.String r2 = "&bull;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 53
            r0[r2] = r1
            java.lang.String r1 = "…"
            java.lang.String r2 = "&hellip;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 54
            r0[r2] = r1
            java.lang.String r1 = "′"
            java.lang.String r2 = "&prime;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 55
            r0[r2] = r1
            java.lang.String r1 = "″"
            java.lang.String r2 = "&Prime;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 56
            r0[r2] = r1
            java.lang.String r1 = "‾"
            java.lang.String r2 = "&oline;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 57
            r0[r2] = r1
            java.lang.String r1 = "⁄"
            java.lang.String r2 = "&frasl;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 58
            r0[r2] = r1
            java.lang.String r1 = "℘"
            java.lang.String r2 = "&weierp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 59
            r0[r2] = r1
            java.lang.String r1 = "ℑ"
            java.lang.String r2 = "&image;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 60
            r0[r2] = r1
            java.lang.String r1 = "ℜ"
            java.lang.String r2 = "&real;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 61
            r0[r2] = r1
            java.lang.String r1 = "™"
            java.lang.String r2 = "&trade;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 62
            r0[r2] = r1
            java.lang.String r1 = "ℵ"
            java.lang.String r2 = "&alefsym;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 63
            r0[r2] = r1
            java.lang.String r1 = "←"
            java.lang.String r2 = "&larr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 64
            r0[r2] = r1
            java.lang.String r1 = "↑"
            java.lang.String r2 = "&uarr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 65
            r0[r2] = r1
            java.lang.String r1 = "→"
            java.lang.String r2 = "&rarr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 66
            r0[r2] = r1
            java.lang.String r1 = "↓"
            java.lang.String r2 = "&darr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 67
            r0[r2] = r1
            java.lang.String r1 = "↔"
            java.lang.String r2 = "&harr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 68
            r0[r2] = r1
            java.lang.String r1 = "↵"
            java.lang.String r2 = "&crarr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 69
            r0[r2] = r1
            java.lang.String r1 = "⇐"
            java.lang.String r2 = "&lArr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 70
            r0[r2] = r1
            java.lang.String r1 = "⇑"
            java.lang.String r2 = "&uArr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 71
            r0[r2] = r1
            java.lang.String r1 = "⇒"
            java.lang.String r2 = "&rArr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 72
            r0[r2] = r1
            java.lang.String r1 = "⇓"
            java.lang.String r2 = "&dArr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 73
            r0[r2] = r1
            java.lang.String r1 = "⇔"
            java.lang.String r2 = "&hArr;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 74
            r0[r2] = r1
            java.lang.String r1 = "∀"
            java.lang.String r2 = "&forall;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 75
            r0[r2] = r1
            java.lang.String r1 = "∂"
            java.lang.String r2 = "&part;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 76
            r0[r2] = r1
            java.lang.String r1 = "∃"
            java.lang.String r2 = "&exist;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 77
            r0[r2] = r1
            java.lang.String r1 = "∅"
            java.lang.String r2 = "&empty;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 78
            r0[r2] = r1
            java.lang.String r1 = "∇"
            java.lang.String r2 = "&nabla;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 79
            r0[r2] = r1
            java.lang.String r1 = "∈"
            java.lang.String r2 = "&isin;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 80
            r0[r2] = r1
            java.lang.String r1 = "∉"
            java.lang.String r2 = "&notin;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 81
            r0[r2] = r1
            java.lang.String r1 = "∋"
            java.lang.String r2 = "&ni;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 82
            r0[r2] = r1
            java.lang.String r1 = "∏"
            java.lang.String r2 = "&prod;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 83
            r0[r2] = r1
            java.lang.String r1 = "∑"
            java.lang.String r2 = "&sum;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 84
            r0[r2] = r1
            java.lang.String r1 = "−"
            java.lang.String r2 = "&minus;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 85
            r0[r2] = r1
            java.lang.String r1 = "∗"
            java.lang.String r2 = "&lowast;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 86
            r0[r2] = r1
            java.lang.String r1 = "√"
            java.lang.String r2 = "&radic;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 87
            r0[r2] = r1
            java.lang.String r1 = "∝"
            java.lang.String r2 = "&prop;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 88
            r0[r2] = r1
            java.lang.String r1 = "∞"
            java.lang.String r2 = "&infin;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 89
            r0[r2] = r1
            java.lang.String r1 = "∠"
            java.lang.String r2 = "&ang;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 90
            r0[r2] = r1
            java.lang.String r1 = "∧"
            java.lang.String r2 = "&and;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 91
            r0[r2] = r1
            java.lang.String r1 = "∨"
            java.lang.String r2 = "&or;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 92
            r0[r2] = r1
            java.lang.String r1 = "∩"
            java.lang.String r2 = "&cap;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 93
            r0[r2] = r1
            java.lang.String r1 = "∪"
            java.lang.String r2 = "&cup;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 94
            r0[r2] = r1
            java.lang.String r1 = "∫"
            java.lang.String r2 = "&int;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 95
            r0[r2] = r1
            java.lang.String r1 = "∴"
            java.lang.String r2 = "&there4;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 96
            r0[r2] = r1
            java.lang.String r1 = "∼"
            java.lang.String r2 = "&sim;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 97
            r0[r2] = r1
            java.lang.String r1 = "≅"
            java.lang.String r2 = "&cong;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 98
            r0[r2] = r1
            java.lang.String r1 = "≈"
            java.lang.String r2 = "&asymp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 99
            r0[r2] = r1
            java.lang.String r1 = "≠"
            java.lang.String r2 = "&ne;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 100
            r0[r2] = r1
            java.lang.String r1 = "≡"
            java.lang.String r2 = "&equiv;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 101(0x65, float:1.42E-43)
            r0[r2] = r1
            java.lang.String r1 = "≤"
            java.lang.String r2 = "&le;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 102(0x66, float:1.43E-43)
            r0[r2] = r1
            java.lang.String r1 = "≥"
            java.lang.String r2 = "&ge;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 103(0x67, float:1.44E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊂"
            java.lang.String r2 = "&sub;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 104(0x68, float:1.46E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊃"
            java.lang.String r2 = "&sup;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 105(0x69, float:1.47E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊄"
            java.lang.String r2 = "&nsub;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 106(0x6a, float:1.49E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊆"
            java.lang.String r2 = "&sube;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 107(0x6b, float:1.5E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊇"
            java.lang.String r2 = "&supe;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 108(0x6c, float:1.51E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊕"
            java.lang.String r2 = "&oplus;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 109(0x6d, float:1.53E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊗"
            java.lang.String r2 = "&otimes;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 110(0x6e, float:1.54E-43)
            r0[r2] = r1
            java.lang.String r1 = "⊥"
            java.lang.String r2 = "&perp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 111(0x6f, float:1.56E-43)
            r0[r2] = r1
            java.lang.String r1 = "⋅"
            java.lang.String r2 = "&sdot;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 112(0x70, float:1.57E-43)
            r0[r2] = r1
            java.lang.String r1 = "⌈"
            java.lang.String r2 = "&lceil;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 113(0x71, float:1.58E-43)
            r0[r2] = r1
            java.lang.String r1 = "⌉"
            java.lang.String r2 = "&rceil;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 114(0x72, float:1.6E-43)
            r0[r2] = r1
            java.lang.String r1 = "⌊"
            java.lang.String r2 = "&lfloor;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 115(0x73, float:1.61E-43)
            r0[r2] = r1
            java.lang.String r1 = "⌋"
            java.lang.String r2 = "&rfloor;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 116(0x74, float:1.63E-43)
            r0[r2] = r1
            java.lang.String r1 = "〈"
            java.lang.String r2 = "&lang;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 117(0x75, float:1.64E-43)
            r0[r2] = r1
            java.lang.String r1 = "〉"
            java.lang.String r2 = "&rang;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 118(0x76, float:1.65E-43)
            r0[r2] = r1
            java.lang.String r1 = "◊"
            java.lang.String r2 = "&loz;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 119(0x77, float:1.67E-43)
            r0[r2] = r1
            java.lang.String r1 = "♠"
            java.lang.String r2 = "&spades;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 120(0x78, float:1.68E-43)
            r0[r2] = r1
            java.lang.String r1 = "♣"
            java.lang.String r2 = "&clubs;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 121(0x79, float:1.7E-43)
            r0[r2] = r1
            java.lang.String r1 = "♥"
            java.lang.String r2 = "&hearts;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 122(0x7a, float:1.71E-43)
            r0[r2] = r1
            java.lang.String r1 = "♦"
            java.lang.String r2 = "&diams;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 123(0x7b, float:1.72E-43)
            r0[r2] = r1
            java.lang.String r1 = "Œ"
            java.lang.String r2 = "&OElig;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 124(0x7c, float:1.74E-43)
            r0[r2] = r1
            java.lang.String r1 = "œ"
            java.lang.String r2 = "&oelig;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 125(0x7d, float:1.75E-43)
            r0[r2] = r1
            java.lang.String r1 = "Š"
            java.lang.String r2 = "&Scaron;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 126(0x7e, float:1.77E-43)
            r0[r2] = r1
            java.lang.String r1 = "š"
            java.lang.String r2 = "&scaron;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 127(0x7f, float:1.78E-43)
            r0[r2] = r1
            java.lang.String r1 = "Ÿ"
            java.lang.String r2 = "&Yuml;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 128(0x80, float:1.794E-43)
            r0[r2] = r1
            java.lang.String r1 = "ˆ"
            java.lang.String r2 = "&circ;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 129(0x81, float:1.81E-43)
            r0[r2] = r1
            java.lang.String r1 = "˜"
            java.lang.String r2 = "&tilde;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 130(0x82, float:1.82E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u2002"
            java.lang.String r2 = "&ensp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 131(0x83, float:1.84E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u2003"
            java.lang.String r2 = "&emsp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 132(0x84, float:1.85E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u2009"
            java.lang.String r2 = "&thinsp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 133(0x85, float:1.86E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u200c"
            java.lang.String r2 = "&zwnj;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 134(0x86, float:1.88E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u200d"
            java.lang.String r2 = "&zwj;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 135(0x87, float:1.89E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u200e"
            java.lang.String r2 = "&lrm;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 136(0x88, float:1.9E-43)
            r0[r2] = r1
            java.lang.String r1 = "\u200f"
            java.lang.String r2 = "&rlm;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 137(0x89, float:1.92E-43)
            r0[r2] = r1
            java.lang.String r1 = "–"
            java.lang.String r2 = "&ndash;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 138(0x8a, float:1.93E-43)
            r0[r2] = r1
            java.lang.String r1 = "—"
            java.lang.String r2 = "&mdash;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 139(0x8b, float:1.95E-43)
            r0[r2] = r1
            java.lang.String r1 = "‘"
            java.lang.String r2 = "&lsquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 140(0x8c, float:1.96E-43)
            r0[r2] = r1
            java.lang.String r1 = "’"
            java.lang.String r2 = "&rsquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 141(0x8d, float:1.98E-43)
            r0[r2] = r1
            java.lang.String r1 = "‚"
            java.lang.String r2 = "&sbquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 142(0x8e, float:1.99E-43)
            r0[r2] = r1
            java.lang.String r1 = "“"
            java.lang.String r2 = "&ldquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 143(0x8f, float:2.0E-43)
            r0[r2] = r1
            java.lang.String r1 = "”"
            java.lang.String r2 = "&rdquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 144(0x90, float:2.02E-43)
            r0[r2] = r1
            java.lang.String r1 = "„"
            java.lang.String r2 = "&bdquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 145(0x91, float:2.03E-43)
            r0[r2] = r1
            java.lang.String r1 = "†"
            java.lang.String r2 = "&dagger;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 146(0x92, float:2.05E-43)
            r0[r2] = r1
            java.lang.String r1 = "‡"
            java.lang.String r2 = "&Dagger;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 147(0x93, float:2.06E-43)
            r0[r2] = r1
            java.lang.String r1 = "‰"
            java.lang.String r2 = "&permil;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 148(0x94, float:2.07E-43)
            r0[r2] = r1
            java.lang.String r1 = "‹"
            java.lang.String r2 = "&lsaquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 149(0x95, float:2.09E-43)
            r0[r2] = r1
            java.lang.String r1 = "›"
            java.lang.String r2 = "&rsaquo;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 150(0x96, float:2.1E-43)
            r0[r2] = r1
            java.lang.String r1 = "€"
            java.lang.String r2 = "&euro;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r2 = 151(0x97, float:2.12E-43)
            r0[r2] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE = r0
            java.lang.String[][] r0 = new java.lang.String[r7][]
            java.lang.String r1 = "\""
            java.lang.String r2 = "&quot;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r3] = r1
            java.lang.String r1 = "&"
            java.lang.String r2 = "&amp;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r4] = r1
            java.lang.String r1 = "<"
            java.lang.String r2 = "&lt;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r5] = r1
            java.lang.String r1 = ">"
            java.lang.String r2 = "&gt;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r6] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE = r0
            java.lang.String[][] r0 = new java.lang.String[r4][]
            java.lang.String r1 = "'"
            java.lang.String r2 = "&apos;"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r3] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE = r0
            java.lang.String[][] r0 = new java.lang.String[r8][]
            java.lang.String r1 = "\b"
            java.lang.String r2 = "\\b"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r3] = r1
            java.lang.String r1 = "\n"
            java.lang.String r2 = "\\n"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r4] = r1
            java.lang.String r1 = "\t"
            java.lang.String r2 = "\\t"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r5] = r1
            java.lang.String r1 = "\f"
            java.lang.String r2 = "\\f"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r6] = r1
            java.lang.String r1 = "\r"
            java.lang.String r2 = "\\r"
            java.lang.String[] r1 = new java.lang.String[]{r1, r2}
            r0[r7] = r1
            org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE = r0
            java.lang.String[][] r0 = invert(r0)
            org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE = r0
            return
    }

    public EntityArrays() {
            r0 = this;
            r0.<init>()
            return
    }

    public static java.lang.String[][] APOS_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.APOS_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] APOS_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.APOS_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] BASIC_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.BASIC_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] BASIC_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.BASIC_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] HTML40_EXTENDED_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] HTML40_EXTENDED_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.HTML40_EXTENDED_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] ISO8859_1_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] ISO8859_1_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.ISO8859_1_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] JAVA_CTRL_CHARS_ESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_ESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] JAVA_CTRL_CHARS_UNESCAPE() {
            java.lang.String[][] r0 = org.apache.commons.lang3.text.translate.EntityArrays.JAVA_CTRL_CHARS_UNESCAPE
            java.lang.Object r0 = r0.clone()
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            return r0
    }

    public static java.lang.String[][] invert(java.lang.String[][] r6) {
            int r0 = r6.length
            r1 = 2
            int[] r2 = new int[r1]
            r3 = 1
            r2[r3] = r1
            r1 = 0
            r2[r1] = r0
            java.lang.Class<java.lang.String> r0 = java.lang.String.class
            java.lang.Object r0 = java.lang.reflect.Array.newInstance(r0, r2)
            java.lang.String[][] r0 = (java.lang.String[][]) r0
            r2 = 0
        L13:
            int r4 = r6.length
            if (r2 >= r4) goto L29
            r4 = r0[r2]
            r5 = r6[r2]
            r5 = r5[r3]
            r4[r1] = r5
            r4 = r0[r2]
            r5 = r6[r2]
            r5 = r5[r1]
            r4[r3] = r5
            int r2 = r2 + 1
            goto L13
        L29:
            return r0
    }
}
